### ISSUE TITLE
!!TOKEN STEALER DONT INSTALL!!

### ISSUE THREAD

**Issue by Pr0xyblade** [DiscordFucker/DFucker-Grabber#2]
very basic stealer, checks all possible discord instalation locations and yoinks tokens. Also detected by windows av :gay:

![image](https://user-images.githubusercontent.com/72248782/108679821-f2214700-7551-11eb-937c-2cb6ef76a6b2.png)

You can also pull this:
h t t p s : / / r a w . g i t h u b u s e r c o n t e n t . c o m / D i s c o r d F u c k e r / A s s e t s / m a i n / A p i L i n k . t x t 9/ i n j e c t o r / p e r m a n a n t ? w e b h o o k 

which is https://raw.githubusercontent.com/DiscordFucker/Assets/main/ApiLink.txt9/injector/permanant?webhook
if you delete everything after ApiLink.txt and open that, you get this text pop up: http://1.api.fucker.today/v1
opening that website is a black githubpages site

**Comment by Azorixxx** [comment]
Yep, and the grabber is here:  %appdata%\discord\0.0.309\modules\discord_desktop_core in the index ( who is obfuscate)
(or the new update from discord, it depends of your version of discord, but is located on the discord files shit) 

Thanks you for approving the file is grabber, now I hope nobody will install this shit really

**Comment by Stanley-GF** [comment]
ok so stfu idc what u are talking :)

**Comment by Azorixxx** [comment]
> ok so stfu idc what u are talking :)

Yes because your software is totally bad & detected by VirusTotal noob

**Comment by Stanley-GF** [comment]
ok try to do the same idiot

**Comment by Stanley-GF** [comment]
ah mais t'es français
essaye de faire la meme cnrd

**Comment by zzzjockzzz** [comment]
don't install this. random Swedish asshole gets access to your shit.

**Comment by Stanley-GF** [comment]
ok i close issues.

**Comment by Azorixxx** [comment]
Bah Alors Stanley sa ferme les issues

**Comment by Stanley-GF** [comment]
Onela

**Comment by Pr0xyblade** [comment]
SAzorixxx 4 days ago
Yep, and the grabber is here: %appdata%\discord\0.0.309\modules\discord_desktop_core in the index ( who is obfuscate)
(or the new update from discord, it depends of your version of discord, but is located on the discord files shit)

Thanks you for approving the file is grabber, now I hope nobody will install this shit really
